Assistant checkpoint: Fix metaclass conflict in BaseOperationThread
Assistant generated file changes:
- threads/base_thread.py: Fix metaclass conflict by creating custom metaclass

---

User prompt:

:\ProgramData\anaconda3\python.exe C:\Users\PCP-Zymoptiq\PycharmProjects\PythonProject2\main.py
Traceback (most recent call last):
  File "C:\Users\PCP-Zymoptiq\PycharmProjects\PythonProject2\main.py", line 13, in <module>
    from views.main_window import DriveExplorerMainWindow
  File "C:\Users\PCP-Zymoptiq\PycharmProjects\PythonProject2\views\__init__.py", line 5, in <module>
    from .main_window import DriveExplorerMainWindow
  File "C:\Users\PCP-Zymoptiq\PycharmProjects\PythonProject2\views\main_window.py", line 22, in <module>
    from threads.file_load_threads import LocalFileLoadThread, DriveFileLoadThread
  File "C:\Users\PCP-Zymoptiq\PycharmProjects\PythonProject2\threads\__init__.py", line 6, in <module>
    from .base_thread import BaseOperationThread
  File "C:\Users\PCP-Zymoptiq\PycharmProjects\PythonProject2\threads\base_thread.py", line 14, in <module>
    class BaseOperationThread(QThread, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: 0ff8c3a3-2e89-49b7-b88b-1629c8b9c504